### ISSUE TITLE
Can't parse URL

### ISSUE THREAD

**Issue by AzuKaOwO** [gan-of-culture/go-hentai-scraper#15]
C:\Users\****\go-hentai-scraper>go-hentai-scraper -O D:\test https://nhentai.net/g/344322/

C:\Users\****\go-hentai-scraper>go-hentai-scraper -O C:\Users\****\Desktop\test https://nhentai.net/g/344322/
2021/03/22 16:04:11 Can't parse URL

C:\Users\****\go-hentai-scraper>go-hentai-scraper -O C:\Users\****\Desktop\test https://nhentai.net/g/344322
2021/03/22 16:04:14 Can't parse URL

C:\Users\****\go-hentai-scraper>go-hentai-scraper -

O C:\Users\****\Desktop\test http://nhentai.net/g/344322
2021/03/22 16:04:34 Can't parse URL

C:\Users\****\go-hentai-scraper>
 first try nothing happen (in external hard disk)
 

![image](https://user-images.githubusercontent.com/60112822/112011636-bc5b8800-8b28-11eb-936b-53ba6263ff66.png)

**Comment by gan-of-culture** [comment]
As soon as this fix goes on master please try again. 

try it like this please go-hentai-scraper -O "D:\test\" https://nhentai.net/g/344322/
