### ISSUE TITLE
[ERROR] <Pls help>

### ISSUE THREAD

**Issue by Raycchi** [gan-of-culture/go-hentai-scraper#27]
I build it and tried to run on cmd i get this error,
and when i tried the executable, doesnt open for more than 1 msec 
Can u help me pls ?

CMD error:

D:\Scripts\go-hentai-scraper-master\go-hentai-scraper-master>go run main.go
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.main()
        D:/Scripts/go-hentai-scraper-master/go-hentai-scraper-master/main.go:95 +0xb9
exit status 2

**Comment by gan-of-culture** [comment]
It's a command line program if you run it via the console or via go run main.go you always need to supply a url of the thing you want to download for example in your console run:

go run main.go https://...

**Comment by Raycchi** [comment]
hanime.tv videos

**Comment by gan-of-culture** [comment]
Then just do

```bash
go run main.go https://hanime.tv/videos/hentai/toilet-no-hanako-san-vs-kukkyou-taimashi-2
```

or 

```bash
go-hentai-scraper.exe https://hanime.tv/videos/hentai/toilet-no-hanako-san-vs-kukkyou-taimashi-2
```

and of couse use the URL of the video you want to download instead

**Comment by Raycchi** [comment]
Okay, worked out, sorry for that.
Thank you.
